<div class="panel-body"> <div class="row kqborder kqvertimarginw" style="padding-left: 10px;">
<div class="fb-like col-sm-2 kqsocial_inner fb_iframe_widget" data-href="https://www.facebook.com/fanpageketqua/" data-layout="button_count" data-action="like" data-show-faces="true" data-share="false" fb-xfbml-state="rendered" fb-iframe-plugin-query="action=like&amp;app_id=1022589457870723&amp;container_width=147&amp;href=https%3A%2F%2Fwww.facebook.com%2Ffanpageketqua%2F&amp;layout=button_count&amp;locale=vi_VN&amp;sdk=joey&amp;share=false&amp;show_faces=true"><span style="vertical-align: bottom; width: 0px; height: 0px;"><iframe name="f16e4922ac4633c" width="1000px" height="1000px" frameborder="0" allowtransparency="true" allowfullscreen="true" scrolling="no" allow="encrypted-media" title="fb:like Facebook Social Plugin" src="https://www.facebook.com/v2.5/plugins/like.php?action=like&amp;app_id=1022589457870723&amp;channel=http%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbiter%2Fr%2FoVjM2wVZ10b.js%3Fversion%3D42%23cb%3Df1865d783e572c%26domain%3Dketqua.net%26origin%3Dhttp%253A%252F%252Fketqua.net%252Ff23ab5265a49878%26relation%3Dparent.parent&amp;container_width=147&amp;href=https%3A%2F%2Fwww.facebook.com%2Ffanpageketqua%2F&amp;layout=button_count&amp;locale=vi_VN&amp;sdk=joey&amp;share=false&amp;show_faces=true" style="border: none; visibility: visible; width: 0px; height: 0px;" class=""></iframe></span></div>
<div class="fb-share-button col-sm-2 kqsocial_inner fb_iframe_widget" data-href="http://ketqua.net/" data-layout="button_count" fb-xfbml-state="rendered" fb-iframe-plugin-query="app_id=1022589457870723&amp;container_width=148&amp;href=http%3A%2F%2Fketqua.net%2F&amp;layout=button_count&amp;locale=vi_VN&amp;sdk=joey"><span style="vertical-align: bottom; width: 78px; height: 20px;"><iframe name="f1805a498160a3c" width="1000px" height="1000px" frameborder="0" allowtransparency="true" allowfullscreen="true" scrolling="no" allow="encrypted-media" title="fb:share_button Facebook Social Plugin" src="https://www.facebook.com/v2.5/plugins/share_button.php?app_id=1022589457870723&amp;channel=http%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbiter%2Fr%2FoVjM2wVZ10b.js%3Fversion%3D42%23cb%3Df306e17844f08%26domain%3Dketqua.net%26origin%3Dhttp%253A%252F%252Fketqua.net%252Ff23ab5265a49878%26relation%3Dparent.parent&amp;container_width=148&amp;href=http%3A%2F%2Fketqua.net%2F&amp;layout=button_count&amp;locale=vi_VN&amp;sdk=joey" style="border: none; visibility: visible; width: 78px; height: 20px;" class=""></iframe></span></div>
<script src="https://apis.google.com/js/platform.js" async="" defer="" type="" gapi_processed="true">
  {lang: 'vi'}
</script>
<div style="text-indent: 0px; margin: 0px; padding: 0px; background: transparent; border-style: none; float: none; line-height: normal; font-size: 1px; vertical-align: baseline; display: inline-block; width: 64px; height: 20px;" id="___plus_0"><iframe ng-non-bindable="" frameborder="0" hspace="0" marginheight="0" marginwidth="0" scrolling="no" style="position: static; top: 0px; width: 64px; margin: 0px; border-style: none; left: 0px; visibility: visible; height: 20px;" tabindex="0" vspace="0" width="100%" id="I0_1527503068357" name="I0_1527503068357" src="https://apis.google.com/u/0/se/0/_/+1/sharebutton?plusShare=true&amp;usegapi=1&amp;action=share&amp;annotation=bubble&amp;hl=vi&amp;origin=http%3A%2F%2Fketqua.net&amp;url=http%3A%2F%2Fketqua.net%2Fso-ket-qua&amp;gsrc=3p&amp;ic=1&amp;jsh=m%3B%2F_%2Fscs%2Fapps-static%2F_%2Fjs%2Fk%3Doz.gapi.en.oKdW7bnNCkA.O%2Fm%3D__features__%2Fam%3DQQE%2Frt%3Dj%2Fd%3D1%2Frs%3DAGLTcCN21chCqe-J_uS07QYyqnqbGguhpg#_methods=onPlusOne%2C_ready%2C_close%2C_open%2C_resizeMe%2C_renderstart%2Concircled%2Cdrefresh%2Cerefresh%2Conload&amp;id=I0_1527503068357&amp;_gfid=I0_1527503068357&amp;parent=http%3A%2F%2Fketqua.net&amp;pfname=&amp;rpctoken=31932702" data-gapiattached="true" title="G+"></iframe></div>
</div><div class="row">
<div class="col-sm-5 col-offset-2" style="margin-left: 1px;">
<a rel="nofollow" href="http://cacuoc24.net/" target="_blank"> <img src="http://img.ketqua.net/images/2017/06/08/14f1dd05cb44f87cffae3c3d9c48d735.gif" alt="dang ky 188bet" width="730" height="90" style="margin-bottom: 5px"></a>
<a rel="nofollow" href="https://cacuoc247.com/" target="_blank"> <img src="http://img.ketqua.net/images/2017/06/29/28586cf744c7ff3534aad6d4e31e2201.gif" alt="dang ky m88" width="730" height="90" style="margin-bottom: 5px"></a>
</div>
</div> 
<div class="kqbackground vien">
<div id="outer_result_btr">
<div class="result_div" id="result_btr">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_btr" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">22-05-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">835548</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">93965</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">55911</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">68333</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">96747</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">80349</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">89569</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">94674</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">29193</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">59650</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">34183</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">96613</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">8653</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">6649</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">5307</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">9536</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">583</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">90</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_btr">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">07; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">11; 13; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">33; 36; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">47; <span class="maudo">48</span>; 49; 49; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">50; 53; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">65; 69; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">74; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank">83; 83; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">90; 93; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_btr">
<div class="result_div" id="result_btr">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_btr" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">15-05-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">712739</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">44784</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">29612</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">81474</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">44403</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">03154</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">19514</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">54967</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">00214</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">50462</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">20751</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">18357</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">9769</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">0993</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">8004</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">3803</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">456</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">19</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_btr">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">03; 03; 04; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">12; 14; 14; 19; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank"><span class="maudo">39</span>; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">51; 54; 56; 57; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">62; 67; 69; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">74; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank">84; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">93; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_btr">
<div class="result_div" id="result_btr">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_btr" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">08-05-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">348921</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">21332</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">60082</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">78410</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">77712</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">76649</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">60435</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">31076</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">97175</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">08419</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">65465</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">38763</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">3234</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">3071</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">1354</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">0910</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">236</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">04</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_btr">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">04; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">10; 10; 12; 19; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank"><span class="maudo">21</span>; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">32; 34; 35; 36; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">49; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">54; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">63; 65; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">71; 75; 76; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank">82; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank"></td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_btr">
<div class="result_div" id="result_btr">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_btr" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">01-05-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">681123</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">05130</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">41506</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">20315</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">31614</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">17874</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">34119</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">64424</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">88845</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">68378</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">11636</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">93548</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">5863</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">0154</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">8968</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">3085</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">483</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">15</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_btr">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">06; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">14; 15; 15; 19; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank"><span class="maudo">23</span>; 24; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">30; 36; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">45; 48; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">54; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">63; 68; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">74; 78; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank">83; 85; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank"></td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_btr">
<div class="result_div" id="result_btr">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_btr" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">24-04-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">437083</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">49768</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">52965</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">83652</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">11092</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">96703</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">67119</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">91283</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">00963</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">23221</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">00098</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">73362</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">4100</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">3335</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">0284</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">0876</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">485</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">09</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_btr">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">00; 03; 09; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">19; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">21; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">35; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">52; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">62; 63; 65; 68; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">76; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank"><span class="maudo">83</span>; 83; 84; 85; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">92; 98; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_btr">
<div class="result_div" id="result_btr">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_btr" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">17-04-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">015361</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">73613</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">93866</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">82828</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">19599</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">83156</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">11737</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">18687</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">45564</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">29749</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">52064</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">23978</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">3210</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">2767</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">6925</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">1408</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">523</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">35</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_btr">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">08; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">10; 13; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">23; 25; 28; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">35; 37; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">49; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">56; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank"><span class="maudo">61</span>; 64; 64; 66; 67; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">78; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank">87; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">99; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_btr">
<div class="result_div" id="result_btr">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_btr" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">10-04-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">662720</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">98862</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">19370</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">13777</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">35481</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">63073</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">86892</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">09868</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">30543</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">66717</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">71096</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">40896</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">3252</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">9161</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">8606</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">6745</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">946</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">69</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_btr">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">06; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">17; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank"><span class="maudo">20</span>; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">43; 45; 46; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">52; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">61; 62; 68; 69; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">70; 73; 77; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank">81; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">92; 96; 96; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_btr">
<div class="result_div" id="result_btr">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_btr" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">03-04-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">397316</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">09806</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">17863</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">98924</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">25053</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">47615</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">82809</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">11158</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">20577</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">00750</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">31730</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">55943</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">0420</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">0707</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">3848</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">9832</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">549</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">39</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_btr">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">06; 07; 09; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">15; <span class="maudo">16</span>; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">20; 24; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">30; 32; 39; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">43; 48; 49; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">50; 53; 58; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">63; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">77; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank"></td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_btr">
<div class="result_div" id="result_btr">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_btr" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">27-03-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">151452</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">51755</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">69013</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">75248</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">96583</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">53715</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">20854</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">21806</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">18850</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">72703</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">95875</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">49719</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">3892</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">5236</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">2857</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">6853</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">924</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">17</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_btr">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">03; 06; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">13; 15; 17; 19; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">24; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">36; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">48; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">50; <span class="maudo">52</span>; 53; 54; 55; 57; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">75; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank">83; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">92; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_btr">
<div class="result_div" id="result_btr">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_btr" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">20-03-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">130340</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">28440</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">99255</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">03164</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">71924</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">91923</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">22478</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">65951</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">03306</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">96896</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">36783</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">86300</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">2466</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">9633</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">2379</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">7564</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">503</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">40</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_btr">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">00; 03; 06; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">23; 24; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">33; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank"><span class="maudo">40</span>; 40; 40; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">51; 55; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">64; 64; 66; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">78; 79; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank">83; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">96; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_btr">
<div class="result_div" id="result_btr">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_btr" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">13-03-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">746307</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">51516</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">08834</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">85087</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">64553</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">22982</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">62842</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">92241</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">99282</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">34964</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">54064</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">30385</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">3473</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">6146</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">9234</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">0751</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">564</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">34</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_btr">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank"><span class="maudo">07</span>; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">16; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">34; 34; 34; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">41; 42; 46; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">51; 53; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">64; 64; 64; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">73; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank">82; 82; 85; 87; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank"></td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_btr">
<div class="result_div" id="result_btr">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_btr" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">06-03-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">953199</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">92996</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">10904</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">46243</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">56723</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">10363</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">13362</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">50170</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">02923</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">13942</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">93768</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">33105</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">6520</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">6192</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">3854</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">5003</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">039</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">49</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_btr">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">03; 04; 05; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">20; 23; 23; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">39; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">42; 43; 49; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">54; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">62; 63; 68; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">70; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">92; 96; <span class="maudo">99</span>; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_btr">
<div class="result_div" id="result_btr">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_btr" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">27-02-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">825832</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">93730</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">79751</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">76481</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">58554</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">22970</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">02231</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">38981</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">33401</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">70773</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">84471</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">39783</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">8323</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">2944</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">5962</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">8610</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">788</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">00</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_btr">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">00; 01; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">10; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">23; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">30; 31; <span class="maudo">32</span>; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">44; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">51; 54; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">62; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">70; 71; 73; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank">81; 81; 83; 88; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank"></td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_btr">
<div class="result_div" id="result_btr">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_btr" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">20-02-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">089860</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">15235</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">54239</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">20420</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">89069</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">98470</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">84915</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">45165</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">73106</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">95118</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">38295</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">86299</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">3469</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">3549</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">4596</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">6993</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">024</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">92</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_btr">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">06; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">15; 18; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">20; 24; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">35; 39; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">49; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank"><span class="maudo">60</span>; 65; 69; 69; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">70; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">92; 93; 95; 96; 99; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_btr">
<div class="result_div" id="result_btr">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_btr" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">13-02-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">794648</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">12371</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">73436</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">95917</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">45594</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">50207</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">34200</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">94894</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">07579</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">95191</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">28132</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">56703</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">6494</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">7427</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">4794</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">8680</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">784</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">43</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_btr">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">00; 03; 07; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">17; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">27; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">32; 36; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">43; <span class="maudo">48</span>; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">71; 79; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank">80; 84; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">91; 94; 94; 94; 94; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_btr">
<div class="result_div" id="result_btr">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_btr" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">06-02-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">044083</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">69806</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">05055</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">41323</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">34953</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">14732</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">57770</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">77823</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">90776</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">30939</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">75359</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">06070</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">0983</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">2376</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">2378</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">0523</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">244</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">88</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_btr">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">06; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">23; 23; 23; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">32; 39; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">44; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">53; 55; 59; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">70; 70; 76; 76; 78; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank"><span class="maudo">83</span>; 83; 88; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank"></td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_btr">
<div class="result_div" id="result_btr">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_btr" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">30-01-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">527480</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">61634</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">13802</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">45536</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">66872</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">26443</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">47683</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">21454</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">87208</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">98536</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">80732</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">14194</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">5119</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">8902</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">5174</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">0053</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">340</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">51</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_btr">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">02; 02; 08; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">19; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">32; 34; 36; 36; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">40; 43; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">51; 53; 54; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">72; 74; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank"><span class="maudo">80</span>; 83; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">94; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>
</div>