<div class="kqbackground vien">
<div id="outer_result_hcm">
<div class="result_div" id="result_hcm">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_hcm" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">27-01-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">306051</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">47540</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">47619</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">67258</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">29373</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">55282</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">92293</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">38066</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">35754</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">64829</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">63639</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">52773</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">5317</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">0005</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">3366</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">5500</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">783</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">10</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_hcm">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">00; 05; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">10; 17; 19; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">29; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">39; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">40; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank"><span class="maudo">51</span>; 54; 58; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">66; 66; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">73; 73; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank">82; 83; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">93; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_hcm">
<div class="result_div" id="result_hcm">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_hcm" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">22-01-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">369757</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">20752</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">81209</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">09741</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">91261</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">34061</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">67440</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">70722</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">30442</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">42206</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">41298</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">24385</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">0061</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">4162</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">9262</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">0105</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">011</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">56</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_hcm">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">05; 06; 09; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">11; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">22; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">40; 41; 42; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">52; 56; <span class="maudo">57</span>; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">61; 61; 61; 62; 62; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank">85; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">98; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_hcm">
<div class="result_div" id="result_hcm">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_hcm" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">20-01-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">287290</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">93407</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">85984</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">55053</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">20256</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">02543</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">00821</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">06933</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">58773</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">45648</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">60251</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">47121</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">5429</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">8847</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">9543</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">3544</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">861</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">58</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_hcm">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">07; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">21; 21; 29; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">33; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">43; 43; 44; 47; 48; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">51; 53; 56; 58; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">61; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">73; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank">84; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank"><span class="maudo">90</span>; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_hcm">
<div class="result_div" id="result_hcm">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_hcm" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">15-01-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">512221</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">16713</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">41327</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">89617</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">02643</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">59486</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">93204</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">83935</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">17760</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">37449</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">99491</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">24910</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">4011</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">5058</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">2398</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">0195</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">702</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">01</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_hcm">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">01; 02; 04; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">10; 11; 13; 17; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank"><span class="maudo">21</span>; 27; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">35; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">43; 49; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">58; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">60; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank">86; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">91; 95; 98; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_hcm">
<div class="result_div" id="result_hcm">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_hcm" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">13-01-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">850085</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">02819</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">88661</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">89213</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">87026</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">19162</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">66393</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">94516</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">76063</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">26654</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">71388</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">03383</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">9969</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">3978</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">8725</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">6029</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">991</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">47</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_hcm">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">13; 16; 19; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">25; 26; 29; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">47; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">54; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">61; 62; 63; 69; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">78; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank">83; <span class="maudo">85</span>; 88; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">91; 93; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_hcm">
<div class="result_div" id="result_hcm">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_hcm" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">08-01-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">755452</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">91183</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">93852</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">46249</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">70303</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">60167</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">05730</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">25044</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">80924</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">37270</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">78677</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">44347</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">8338</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">8940</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">2305</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">2446</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">235</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">30</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_hcm">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">03; 05; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">24; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">30; 30; 35; 38; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">40; 44; 46; 47; 49; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank"><span class="maudo">52</span>; 52; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">67; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">70; 77; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank">83; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank"></td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_hcm">
<div class="result_div" id="result_hcm">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_hcm" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">06-01-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">367405</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">96502</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">95782</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">80731</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">21628</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">94890</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">75845</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">72482</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">80745</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">77283</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">67616</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">62143</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">8352</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">6471</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">1805</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">7415</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">273</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">52</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_hcm">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">02; <span class="maudo">05</span>; 05; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">15; 16; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">28; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">31; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">43; 45; 45; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">52; 52; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">71; 73; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank">82; 82; 83; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">90; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_hcm">
<div class="result_div" id="result_hcm">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_hcm" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">01-01-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">526989</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">73247</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">49084</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">83991</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">77028</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">12948</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">51769</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">86882</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">52940</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">67210</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">90391</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">48288</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">5065</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">6438</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">1991</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">6183</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">622</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">81</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_hcm">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">10; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">22; 28; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">38; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">40; 47; 48; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">65; 69; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank">81; 82; 83; 84; 88; <span class="maudo">89</span>; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">91; 91; 91; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_hcm">
<div class="result_div" id="result_hcm">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_hcm" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">30-12-2017</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">648470</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">30633</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">42914</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">15257</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">15477</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">22911</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">36937</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">72974</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">73813</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">37853</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">55162</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">39778</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">1072</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">3734</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">4290</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">4788</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">243</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">17</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_hcm">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">11; 13; 14; 17; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">33; 34; 37; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">43; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">53; 57; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">62; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank"><span class="maudo">70</span>; 72; 74; 77; 78; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank">88; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">90; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_hcm">
<div class="result_div" id="result_hcm">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_hcm" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">25-12-2017</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">539548</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">82452</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">96835</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">47246</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">68558</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">00362</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">16046</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">77844</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">81673</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">54870</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">29001</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">41890</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">7861</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">5807</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">8962</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">0121</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">289</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">22</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_hcm">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">01; 07; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">21; 22; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">35; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">44; 46; 46; <span class="maudo">48</span>; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">52; 58; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">61; 62; 62; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">70; 73; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank">89; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">90; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_hcm">
<div class="result_div" id="result_hcm">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_hcm" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">23-12-2017</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">483147</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">68300</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">86546</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">59052</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">66166</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">52681</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">02305</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">18789</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">20701</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">70522</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">53509</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">97876</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">5151</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">7227</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">3652</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">8478</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">352</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">94</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_hcm">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">00; 01; 05; 09; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">22; 27; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">46; <span class="maudo">47</span>; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">51; 52; 52; 52; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">66; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">76; 78; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank">81; 89; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">94; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_hcm">
<div class="result_div" id="result_hcm">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_hcm" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">18-12-2017</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">422870</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">64605</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">97201</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">79408</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">40748</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">75131</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">02216</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">88013</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">52599</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">86244</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">33855</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">80639</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">3857</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">8820</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">9048</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">3086</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">412</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">88</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_hcm">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">01; 05; 08; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">12; 13; 16; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">20; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">31; 39; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">44; 48; 48; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">55; 57; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank"><span class="maudo">70</span>; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank">86; 88; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">99; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_hcm">
<div class="result_div" id="result_hcm">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_hcm" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">16-12-2017</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">434130</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">66977</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">24589</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">53978</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">17981</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">33642</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">89480</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">67354</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">29401</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">34118</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">79992</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">59310</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">1903</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">8125</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">0632</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">4898</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">503</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">58</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_hcm">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">01; 03; 03; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">10; 18; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">25; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank"><span class="maudo">30</span>; 32; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">42; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">54; 58; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">77; 78; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank">80; 81; 89; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">92; 98; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_hcm">
<div class="result_div" id="result_hcm">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_hcm" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">11-12-2017</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">807921</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">52715</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">52768</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">64531</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">90469</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">35598</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">36663</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">16690</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">66373</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">54787</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">67484</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">45422</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">0415</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">1347</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">4424</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">0774</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">803</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">03</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_hcm">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">03; 03; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">15; 15; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank"><span class="maudo">21</span>; 22; 24; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">31; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">47; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">63; 68; 69; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">73; 74; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank">84; 87; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">90; 98; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_hcm">
<div class="result_div" id="result_hcm">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_hcm" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">09-12-2017</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">364103</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">27790</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">61837</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">00567</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">01451</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">51994</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">29943</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">08230</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">55316</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">64676</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">83064</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">07518</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">6520</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">1741</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">5936</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">6201</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">856</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">55</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_hcm">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">01; <span class="maudo">03</span>; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">16; 18; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">20; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">30; 36; 37; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">41; 43; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">51; 55; 56; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">64; 67; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">76; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">90; 94; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_hcm">
<div class="result_div" id="result_hcm">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_hcm" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">04-12-2017</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">019127</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">34144</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">64145</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">52965</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">80730</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">16281</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">21319</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">50390</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">97990</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">45914</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">81185</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">46493</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">5834</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">7582</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">3871</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">8700</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">919</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">54</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_hcm">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">00; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">14; 19; 19; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank"><span class="maudo">27</span>; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">30; 34; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">44; 45; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">54; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">65; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">71; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank">81; 82; 85; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">90; 90; 93; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_hcm">
<div class="result_div" id="result_hcm">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_hcm" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">02-12-2017</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">711351</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">08328</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">04664</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">98493</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">29363</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">22508</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">56036</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">36809</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">49065</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">92420</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">89464</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">29467</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">3911</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">9266</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">1697</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">8056</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">160</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">48</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_hcm">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">08; 09; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">11; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">20; 28; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">36; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">48; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank"><span class="maudo">51</span>; 56; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">60; 63; 64; 64; 65; 66; 67; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">93; 97; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_hcm">
<div class="result_div" id="result_hcm">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_hcm" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">27-11-2017</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">921984</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">80797</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">62093</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">00003</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">70604</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">83440</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">53406</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">19539</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">85220</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">57906</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">24426</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">49768</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">4867</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">9839</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">8371</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">9512</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">204</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">18</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_hcm">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">03; 04; 04; 06; 06; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">12; 18; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">20; 26; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">39; 39; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">40; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">67; 68; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">71; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank"><span class="maudo">84</span>; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">93; 97; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>
<div class="kqbackground vien">
<div id="outer_result_hcm">
<div class="result_div" id="result_hcm">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_hcm" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">25-11-2017</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">774581</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">55638</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">58475</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">21191</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">09610</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">25041</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">34139</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">05202</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">04925</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">85950</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">04118</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">76149</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">9401</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">0274</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">6275</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">0665</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">199</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">98</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_hcm">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">01; 02; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">10; 18; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">25; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">38; 39; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">41; 49; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">50; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">65; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">74; 75; 75; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank"><span class="maudo">81</span>; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">91; 98; 99; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_hcm">
<div class="result_div" id="result_hcm">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_hcm" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">20-11-2017</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">862409</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">67578</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">06903</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">31690</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">22363</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">18079</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">76135</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">40643</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">82450</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">59658</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">11589</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">06150</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">3426</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">9466</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">3764</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">6674</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">585</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">93</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_hcm">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">03; <span class="maudo">09</span>; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">26; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">35; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">43; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">50; 50; 58; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">63; 64; 66; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">74; 78; 79; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank">85; 89; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">90; 93; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>
</div></div></div>
</div>