<div class="kqbackground vien">
<div id="outer_result_hcm">
<div class="result_div" id="result_hcm">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_hcm" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">18-11-2017</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">015571</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">36537</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">66134</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">17334</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">89952</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">06563</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">09805</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">68271</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">23722</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">10807</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">51453</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">73025</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">3033</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">7642</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">9604</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">1678</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">757</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">93</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_hcm">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">04; 05; 07; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">22; 25; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">33; 34; 34; 37; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">42; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">52; 53; 57; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">63; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank"><span class="maudo">71</span>; 71; 78; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">93; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>