<div class="panel-body"> <div class="row kqborder kqvertimarginw" style="padding-left: 10px;">
<div class="fb-like col-sm-2 kqsocial_inner fb_iframe_widget" data-href="https://www.facebook.com/admketqua.net" data-layout="button_count" data-action="like" data-show-faces="true" data-share="false" fb-xfbml-state="rendered" fb-iframe-plugin-query="action=like&amp;app_id=1022589457870723&amp;container_width=147&amp;href=https%3A%2F%2Fwww.facebook.com%2Fadmketqua.net&amp;layout=button_count&amp;locale=vi_VN&amp;sdk=joey&amp;share=false&amp;show_faces=true"><span style="vertical-align: bottom; width: 79px; height: 20px;"><iframe name="f27114bdd95f0d4" width="1000px" height="1000px" frameborder="0" allowtransparency="true" allowfullscreen="true" scrolling="no" title="fb:like Facebook Social Plugin" src="https://www.facebook.com/v2.5/plugins/like.php?action=like&amp;app_id=1022589457870723&amp;channel=http%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbiter%2Fr%2FlY4eZXm_YWu.js%3Fversion%3D42%23cb%3Dfb92136c3229e4%26domain%3Dketqua.net%26origin%3Dhttp%253A%252F%252Fketqua.net%252Ff11b6091deb6b38%26relation%3Dparent.parent&amp;container_width=147&amp;href=https%3A%2F%2Fwww.facebook.com%2Fadmketqua.net&amp;layout=button_count&amp;locale=vi_VN&amp;sdk=joey&amp;share=false&amp;show_faces=true" style="border: none; visibility: visible; width: 79px; height: 20px;" class=""></iframe></span></div>
<div class="fb-share-button col-sm-2 kqsocial_inner fb_iframe_widget" data-href="http://ketqua.net/" data-layout="button_count" fb-xfbml-state="rendered" fb-iframe-plugin-query="app_id=1022589457870723&amp;container_width=148&amp;href=http%3A%2F%2Fketqua.net%2F&amp;layout=button_count&amp;locale=vi_VN&amp;sdk=joey"><span style="vertical-align: bottom; width: 97px; height: 20px;"><iframe name="f2b9d923799d354" width="1000px" height="1000px" frameborder="0" allowtransparency="true" allowfullscreen="true" scrolling="no" title="fb:share_button Facebook Social Plugin" src="https://www.facebook.com/v2.5/plugins/share_button.php?app_id=1022589457870723&amp;channel=http%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbiter%2Fr%2FlY4eZXm_YWu.js%3Fversion%3D42%23cb%3Df2eb263159727a4%26domain%3Dketqua.net%26origin%3Dhttp%253A%252F%252Fketqua.net%252Ff11b6091deb6b38%26relation%3Dparent.parent&amp;container_width=148&amp;href=http%3A%2F%2Fketqua.net%2F&amp;layout=button_count&amp;locale=vi_VN&amp;sdk=joey" style="border: none; visibility: visible; width: 97px; height: 20px;" class=""></iframe></span></div>
<script data-rocketsrc="https://apis.google.com/js/platform.js" async="" defer="" type="text/rocketscript" data-rocketoptimized="true">
  {lang: 'vi'}
</script>
<div id="___plus_0" style="text-indent: 0px; margin: 0px; padding: 0px; background: transparent; border-style: none; float: none; line-height: normal; font-size: 1px; vertical-align: baseline; display: inline-block; width: 57px; height: 20px;"><iframe ng-non-bindable="" frameborder="0" hspace="0" marginheight="0" marginwidth="0" scrolling="no" style="position: static; top: 0px; width: 57px; margin: 0px; border-style: none; left: 0px; visibility: visible; height: 20px;" tabindex="0" vspace="0" width="100%" id="I1_1511947789079" name="I1_1511947789079" src="https://apis.google.com/u/0/se/0/_/+1/sharebutton?plusShare=true&amp;usegapi=1&amp;action=share&amp;annotation=bubble&amp;origin=http%3A%2F%2Fketqua.net&amp;url=http%3A%2F%2Fketqua.net%2Fso-ket-qua&amp;gsrc=3p&amp;jsh=m%3B%2F_%2Fscs%2Fapps-static%2F_%2Fjs%2Fk%3Doz.gapi.en_US.GHKobDOvFcU.O%2Fm%3D__features__%2Fam%3DAQ%2Frt%3Dj%2Fd%3D1%2Frs%3DAGLTcCPKRaatIrDRe7dHPvJZWwIyPGt8bA#_methods=onPlusOne%2C_ready%2C_close%2C_open%2C_resizeMe%2C_renderstart%2Concircled%2Cdrefresh%2Cerefresh%2Conload&amp;id=I1_1511947789079&amp;_gfid=I1_1511947789079&amp;parent=http%3A%2F%2Fketqua.net&amp;pfname=&amp;rpctoken=18379983" data-gapiattached="true" title="G+"></iframe></div>
</div><div class="row">
<div class="col-sm-5 col-offset-2" style="margin-left: 1px;">
<a rel="nofollow" href="http://cacuoc24.net/" target="_blank"> <img src="http://img.ketqua.net/images/2017/06/08/14f1dd05cb44f87cffae3c3d9c48d735.gif" alt="dang ky 188bet" width="730" height="90" style="margin-bottom: 5px"></a>
<a rel="nofollow" href="http://www.vaobongbet.com/" target="_blank"> <img src="http://img.ketqua.net/images/2017/06/29/28586cf744c7ff3534aad6d4e31e2201.gif" alt="dang ky m88" width="730" height="90" style="margin-bottom: 5px"></a>
</div>
</div> 
<div class="kqbackground vien">
<div id="outer_result_tn">
<div class="result_div" id="result_tn">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_tn" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">23-11-2017</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">289742</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">13177</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">15729</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">91701</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">89427</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">89811</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">94456</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">57540</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">59265</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">48611</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">37667</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">33422</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">1017</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">3761</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">1475</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">2040</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">652</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">83</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_tn">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">01; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">11; 11; 17; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">22; 27; 29; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">40; 40; <span class="maudo">42</span>; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">52; 56; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">61; 65; 67; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">75; 77; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank">83; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank"></td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_tn">
<div class="result_div" id="result_tn">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_tn" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">16-11-2017</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">497822</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">79195</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">22476</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">21371</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">08044</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">18164</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">61208</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">26975</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">48840</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">05709</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">21946</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">46629</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">4435</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">9521</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">3436</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">6822</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">419</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">48</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_tn">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">08; 09; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">19; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">21; <span class="maudo">22</span>; 22; 29; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">35; 36; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">40; 44; 46; 48; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">64; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">71; 75; 76; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">95; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>
</div>