<div class="panel-body"> <div class="row kqborder kqvertimarginw" style="padding-left: 10px;">
<div class="fb-like col-sm-2 kqsocial_inner fb_iframe_widget" data-href="https://www.facebook.com/fanpageketqua/" data-layout="button_count" data-action="like" data-show-faces="true" data-share="false" fb-xfbml-state="rendered" fb-iframe-plugin-query="action=like&amp;app_id=1022589457870723&amp;container_width=147&amp;href=https%3A%2F%2Fwww.facebook.com%2Ffanpageketqua%2F&amp;layout=button_count&amp;locale=vi_VN&amp;sdk=joey&amp;share=false&amp;show_faces=true"><span style="vertical-align: bottom; width: 0px; height: 0px;"><iframe name="f10879dc5a51de8" width="1000px" height="1000px" frameborder="0" allowtransparency="true" allowfullscreen="true" scrolling="no" allow="encrypted-media" title="fb:like Facebook Social Plugin" src="https://www.facebook.com/v2.5/plugins/like.php?action=like&amp;app_id=1022589457870723&amp;channel=http%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbiter%2Fr%2FoVjM2wVZ10b.js%3Fversion%3D42%23cb%3Df1ee19e7ef4d5fc%26domain%3Dketqua.net%26origin%3Dhttp%253A%252F%252Fketqua.net%252Ff14b54df29d20ac%26relation%3Dparent.parent&amp;container_width=147&amp;href=https%3A%2F%2Fwww.facebook.com%2Ffanpageketqua%2F&amp;layout=button_count&amp;locale=vi_VN&amp;sdk=joey&amp;share=false&amp;show_faces=true" style="border: none; visibility: visible; width: 0px; height: 0px;" class=""></iframe></span></div>
<div class="fb-share-button col-sm-2 kqsocial_inner fb_iframe_widget" data-href="http://ketqua.net/" data-layout="button_count" fb-xfbml-state="rendered" fb-iframe-plugin-query="app_id=1022589457870723&amp;container_width=148&amp;href=http%3A%2F%2Fketqua.net%2F&amp;layout=button_count&amp;locale=vi_VN&amp;sdk=joey"><span style="vertical-align: bottom; width: 78px; height: 20px;"><iframe name="f16d0358428a1d8" width="1000px" height="1000px" frameborder="0" allowtransparency="true" allowfullscreen="true" scrolling="no" allow="encrypted-media" title="fb:share_button Facebook Social Plugin" src="https://www.facebook.com/v2.5/plugins/share_button.php?app_id=1022589457870723&amp;channel=http%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbiter%2Fr%2FoVjM2wVZ10b.js%3Fversion%3D42%23cb%3Df131dc333139c54%26domain%3Dketqua.net%26origin%3Dhttp%253A%252F%252Fketqua.net%252Ff14b54df29d20ac%26relation%3Dparent.parent&amp;container_width=148&amp;href=http%3A%2F%2Fketqua.net%2F&amp;layout=button_count&amp;locale=vi_VN&amp;sdk=joey" style="border: none; visibility: visible; width: 78px; height: 20px;" class=""></iframe></span></div>
<script src="https://apis.google.com/js/platform.js" async="" defer="" type="" gapi_processed="true">
  {lang: 'vi'}
</script>
<div id="___plus_0" style="text-indent: 0px; margin: 0px; padding: 0px; background: transparent; border-style: none; float: none; line-height: normal; font-size: 1px; vertical-align: baseline; display: inline-block; width: 67px; height: 20px;"><iframe ng-non-bindable="" frameborder="0" hspace="0" marginheight="0" marginwidth="0" scrolling="no" style="position: static; top: 0px; width: 67px; margin: 0px; border-style: none; left: 0px; visibility: visible; height: 20px;" tabindex="0" vspace="0" width="100%" id="I0_1527502463433" name="I0_1527502463433" src="https://apis.google.com/u/0/se/0/_/+1/sharebutton?plusShare=true&amp;usegapi=1&amp;action=share&amp;annotation=bubble&amp;hl=vi&amp;origin=http%3A%2F%2Fketqua.net&amp;url=http%3A%2F%2Fketqua.net%2Fso-ket-qua&amp;gsrc=3p&amp;ic=1&amp;jsh=m%3B%2F_%2Fscs%2Fapps-static%2F_%2Fjs%2Fk%3Doz.gapi.en.oKdW7bnNCkA.O%2Fm%3D__features__%2Fam%3DQQE%2Frt%3Dj%2Fd%3D1%2Frs%3DAGLTcCN21chCqe-J_uS07QYyqnqbGguhpg#_methods=onPlusOne%2C_ready%2C_close%2C_open%2C_resizeMe%2C_renderstart%2Concircled%2Cdrefresh%2Cerefresh%2Conload&amp;id=I0_1527502463433&amp;_gfid=I0_1527502463433&amp;parent=http%3A%2F%2Fketqua.net&amp;pfname=&amp;rpctoken=16947545" data-gapiattached="true" title="G+"></iframe></div>
</div><div class="row">
<div class="col-sm-5 col-offset-2" style="margin-left: 1px;">
<a rel="nofollow" href="http://cacuoc24.net/" target="_blank"> <img src="http://img.ketqua.net/images/2017/06/08/14f1dd05cb44f87cffae3c3d9c48d735.gif" alt="dang ky 188bet" width="730" height="90" style="margin-bottom: 5px"></a>
<a rel="nofollow" href="https://cacuoc247.com/" target="_blank"> <img src="http://img.ketqua.net/images/2017/06/29/28586cf744c7ff3534aad6d4e31e2201.gif" alt="dang ky m88" width="730" height="90" style="margin-bottom: 5px"></a>
</div>
</div> 
<div class="kqbackground vien">
<div id="outer_result_vt">
<div class="result_div" id="result_vt">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_vt" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">22-05-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">785018</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">01123</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">39346</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">00481</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">77479</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">79007</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">63331</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">34122</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">78615</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">84404</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">59515</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">60905</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">1167</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">9521</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">1149</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">7662</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">505</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">44</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_vt">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">04; 05; 05; 07; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">15; 15; <span class="maudo">18</span>; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">21; 22; 23; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">31; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">44; 46; 49; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">62; 67; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">79; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank">81; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank"></td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_vt">
<div class="result_div" id="result_vt">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_vt" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">15-05-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">067898</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">32578</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">83413</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">57273</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">42422</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">52543</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">35456</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">18575</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">17145</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">64830</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">31446</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">24205</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">7514</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">1658</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">8555</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">9396</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">006</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">98</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_vt">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">05; 06; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">13; 14; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">22; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">30; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">43; 45; 46; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">55; 56; 58; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">73; 75; 78; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">96; <span class="maudo">98</span>; 98; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_vt">
<div class="result_div" id="result_vt">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_vt" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">08-05-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">493208</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">96082</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">28589</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">03188</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">66896</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">17700</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">20398</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">89251</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">41507</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">77627</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">69396</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">38502</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">2155</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">9517</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">1422</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">0304</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">190</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">33</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_vt">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">00; 02; 04; 07; <span class="maudo">08</span>; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">17; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">22; 27; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">33; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">51; 55; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank">82; 88; 89; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">90; 96; 96; 98; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_vt">
<div class="result_div" id="result_vt">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_vt" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">01-05-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">822257</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">51282</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">94047</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">65829</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">98669</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">51255</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">57251</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">41723</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">97928</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">71170</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">78012</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">22896</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">0710</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">7176</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">1084</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">3496</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">673</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">86</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_vt">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">10; 12; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">23; 28; 29; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">47; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">51; 55; <span class="maudo">57</span>; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">69; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">70; 73; 76; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank">82; 84; 86; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">96; 96; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_vt">
<div class="result_div" id="result_vt">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_vt" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">24-04-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">750429</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">71111</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">75366</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">52553</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">14891</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">64252</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">20893</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">91890</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">86470</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">69859</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">11956</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">20008</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">7435</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">3250</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">5927</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">8723</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">432</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">29</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_vt">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">08; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">11; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">23; 27; <span class="maudo">29</span>; 29; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">32; 35; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">50; 52; 53; 56; 59; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">66; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">70; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">90; 91; 93; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_vt">
<div class="result_div" id="result_vt">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_vt" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">17-04-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">747840</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">81254</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">92592</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">33711</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">49950</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">43612</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">29795</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">65035</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">65498</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">90072</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">70990</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">08913</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">4403</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">9353</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">8082</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">2294</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">912</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">12</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_vt">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">03; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">11; 12; 12; 12; 13; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">35; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank"><span class="maudo">40</span>; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">50; 53; 54; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">72; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank">82; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">90; 92; 94; 95; 98; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_vt">
<div class="result_div" id="result_vt">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_vt" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">10-04-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">451744</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">13605</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">97486</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">24628</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">18428</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">93842</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">06436</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">91686</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">48285</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">99393</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">96293</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">33497</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">1818</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">3076</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">3031</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">9529</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">618</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">08</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_vt">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">05; 08; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">18; 18; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">28; 28; 29; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">31; 36; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">42; <span class="maudo">44</span>; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">76; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank">85; 86; 86; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">93; 93; 97; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_vt">
<div class="result_div" id="result_vt">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_vt" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">03-04-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">154215</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">94216</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">40235</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">70765</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">63826</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">92922</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">22823</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">78875</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">98820</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">71085</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">20859</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">93862</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">2404</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">1704</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">5716</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">4601</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">595</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">10</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_vt">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">01; 04; 04; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">10; <span class="maudo">15</span>; 16; 16; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">20; 22; 23; 26; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">35; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">59; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">62; 65; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">75; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank">85; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">95; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_vt">
<div class="result_div" id="result_vt">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_vt" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">27-03-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">142992</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">16716</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">76983</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">11614</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">65108</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">13005</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">66303</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">85147</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">93601</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">66516</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">06564</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">29041</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">6369</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">2971</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">9881</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">6499</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">609</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">76</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_vt">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">01; 03; 05; 08; 09; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">14; 16; 16; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">41; 47; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">64; 69; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">71; 76; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank">81; 83; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank"><span class="maudo">92</span>; 99; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_vt">
<div class="result_div" id="result_vt">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_vt" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">20-03-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">778765</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">05164</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">11616</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">27446</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">05466</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">37393</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">71149</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">80420</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">49342</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">67809</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">55296</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">91177</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">4559</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">1237</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">9881</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">8164</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">067</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">18</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_vt">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">09; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">16; 18; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">20; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">37; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">42; 46; 49; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">59; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">64; 64; <span class="maudo">65</span>; 66; 67; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">77; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank">81; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">93; 96; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_vt">
<div class="result_div" id="result_vt">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_vt" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">13-03-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">717397</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">00623</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">48250</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">92988</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">90731</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">66481</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">24239</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">37490</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">87579</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">30940</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">99935</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">51530</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">3519</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">7959</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">2733</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">9273</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">661</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">58</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_vt">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">19; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">23; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">30; 31; 33; 35; 39; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">40; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">50; 58; 59; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">61; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">73; 79; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank">81; 88; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">90; <span class="maudo">97</span>; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_vt">
<div class="result_div" id="result_vt">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_vt" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">06-03-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">144119</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">93262</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">34833</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">57209</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">17354</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">25187</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">77703</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">08237</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">32274</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">30188</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">97133</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">36985</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">3487</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">3096</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">0872</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">6936</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">755</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">92</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_vt">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">03; 09; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank"><span class="maudo">19</span>; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">33; 33; 36; 37; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">54; 55; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">62; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">72; 74; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank">85; 87; 87; 88; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">92; 96; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_vt">
<div class="result_div" id="result_vt">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_vt" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">27-02-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">157403</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">96581</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">20140</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">79878</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">19973</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">70709</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">43183</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">29765</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">70585</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">67249</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">24651</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">99762</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">5229</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">5909</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">5665</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">7915</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">197</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">96</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_vt">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank"><span class="maudo">03</span>; 09; 09; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">15; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">29; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">40; 49; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">51; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">62; 65; 65; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">73; 78; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank">81; 83; 85; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">96; 97; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_vt">
<div class="result_div" id="result_vt">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_vt" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">20-02-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">726150</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">85853</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">44213</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">64321</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">27581</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">73737</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">95766</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">42865</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">08083</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">28953</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">62310</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">99189</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">9946</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">9615</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">5897</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">1890</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">805</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">58</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_vt">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">05; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">10; 13; 15; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">21; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">37; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">46; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank"><span class="maudo">50</span>; 53; 53; 58; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">65; 66; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank">81; 83; 89; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">90; 97; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_vt">
<div class="result_div" id="result_vt">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_vt" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">13-02-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">289357</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">40503</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">07570</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">27549</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">45773</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">88073</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">31054</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">00716</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">33273</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">71306</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">02834</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">22745</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">3264</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">3118</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">7992</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">8557</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">974</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">57</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_vt">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">03; 06; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">16; 18; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">34; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">45; 49; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">54; <span class="maudo">57</span>; 57; 57; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">64; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">70; 73; 73; 73; 74; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">92; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_vt">
<div class="result_div" id="result_vt">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_vt" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">06-02-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">168043</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">96561</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">84641</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">99347</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">27664</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">86026</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">73302</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">02824</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">70471</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">69778</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">70538</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">66506</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">6381</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">2905</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">4589</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">8540</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">390</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">69</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_vt">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">02; 05; 06; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">24; 26; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">38; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">40; 41; <span class="maudo">43</span>; 47; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank"></td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">61; 64; 69; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">71; 78; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank">81; 89; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">90; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>

<div class="kqbackground vien">
<div id="outer_result_vt">
<div class="result_div" id="result_vt">
<div class="row"><div class="col-sm-6">
<table class="table table-condensed kqcenter kqvertimarginw table-kq-border table-kq-hover table-kq-north-west table-bordered kqbackground table-kq-bold-border" id="result_tab_vt" style="text-align:center;">
<thead>
<tr class="title_row"><td colspan="13" class="dosam chu18">
<span id="result_date">30-01-2018</span></td></tr>
</thead>
<tbody>
<tr><td style="width:22%;vertical-align:middle;font-size:16px;color:red;">Đặc biệt</td><td id="rs_0_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam maudo stop-reload chu30" rs_len="6">748484</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhất</td><td id="rs_1_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">95341</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải nhì</td><td id="rs_2_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="5">54843</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải ba</td><td id="rs_3_0" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">27378</td><td id="rs_3_1" colspan="6" style="width:39%;" class="chu22 gray need_blank vietdam" rs_len="5">19696</td></tr><tr><td rowspan="2" style="width:22%;vertical-align:middle;font-size:16px;">Giải tư</td><td id="rs_4_0" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">75800</td><td id="rs_4_1" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">79918</td><td id="rs_4_2" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">56009</td><td id="rs_4_3" colspan="3" style="width:19.5%;" class="chu22 gray need_blank vietdam" rs_len="5">89464</td></tr><tr><td style="display:none"></td><td id="rs_4_4" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">07037</td><td id="rs_4_5" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">67720</td><td id="rs_4_6" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="5">56350</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải năm</td><td id="rs_5_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="4">0759</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải sáu</td><td id="rs_6_0" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">0446</td><td id="rs_6_1" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">8025</td><td id="rs_6_2" colspan="4" style="width:26%;" class="chu22 gray need_blank vietdam" rs_len="4">6208</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải bảy</td><td id="rs_7_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="3">556</td></tr><tr><td style="width:22%;vertical-align:middle;font-size:16px;">Giải tám</td><td id="rs_8_0" colspan="12" style="width:78%;" class="chu22 gray need_blank vietdam" rs_len="2">84</td></tr> </tbody>
</table>
</div><div class="col-sm-4">

<table class="table table-hover table-bordered table-condensed table-kq-north-west table-kq-border table-kq-bold-border kqbackground table-kq-hover" style="margin-left: 3px;" id="dau_vt">
<thead><tr><td style="width:22%;">Đầu</td><td class="bang_kqnhanh_bold_bottomw">Lô tô</td></tr></thead>
<tbody style="font-weight:bold;">
<tr><td class="dosam chu15 kqcenter">0</td><td id="begin_with_0" class="chu17 need_blank">00; 08; 09; </td></tr><tr><td class="dosam chu15 kqcenter">1</td><td id="begin_with_1" class="chu17 need_blank">18; </td></tr><tr><td class="dosam chu15 kqcenter">2</td><td id="begin_with_2" class="chu17 need_blank">20; 25; </td></tr><tr><td class="dosam chu15 kqcenter">3</td><td id="begin_with_3" class="chu17 need_blank">37; </td></tr><tr><td class="dosam chu15 kqcenter">4</td><td id="begin_with_4" class="chu17 need_blank">41; 43; 46; </td></tr><tr><td class="dosam chu15 kqcenter">5</td><td id="begin_with_5" class="chu17 need_blank">50; 56; 59; </td></tr><tr><td class="dosam chu15 kqcenter">6</td><td id="begin_with_6" class="chu17 need_blank">64; </td></tr><tr><td class="dosam chu15 kqcenter">7</td><td id="begin_with_7" class="chu17 need_blank">78; </td></tr><tr><td class="dosam chu15 kqcenter">8</td><td id="begin_with_8" class="chu17 need_blank"><span class="maudo">84</span>; 84; </td></tr><tr><td class="dosam chu15 kqcenter">9</td><td id="begin_with_9" class="chu17 need_blank">96; </td></tr> </tbody>
</table>
</div></div> </div></div>
</div>
</div>